import { useState } from "react";

import {
    Brain,
    BadgeCheck,
    ShieldCheck,
    FileText,
    CheckCircle2,
    AlertTriangle
} from "lucide-react";

function Section({

    title,

    items,

    icon

}) {

    const Icon = icon;

    return (

        <div className="bg-slate-950 border border-slate-800 rounded-xl p-5">

            <div className="flex items-center gap-2 mb-3">

                <Icon

                    size={18}

                    className="text-cyan-400"

                />

                <h3 className="text-white font-semibold">

                    {title}

                </h3>

            </div>

            {

                items && items.length > 0 ?

                (

                    <ul className="space-y-2">

                        {

                            items.map((item,index)=>(

                                <li

                                    key={index}

                                    className="flex gap-2 text-slate-300 text-sm"

                                >

                                    <span className="text-cyan-400">

                                        •

                                    </span>

                                    <span>

                                        {item}

                                    </span>

                                </li>

                            ))

                        }

                    </ul>

                )

                :

                (

                    <p className="text-slate-500">

                        No information available

                    </p>

                )

            }

        </div>

    );

}

function DecisionCard({

    data

}) {

    const decision = data?.decision || {};

    const [reviewStatus, setReviewStatus] = useState("");

    return (

        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6">

            <div className="flex justify-between items-center mb-6">

                <div>

                    <h2 className="text-2xl font-bold text-white">

                        AI Decision Intelligence

                    </h2>

                    <p className="text-slate-400">

                        Enterprise decision generated by the multi-agent system

                    </p>

                </div>

                <Brain

                    size={40}

                    className="text-cyan-400"

                />

            </div>

            <div className="bg-gradient-to-r from-cyan-950 to-slate-900 border border-cyan-700 rounded-2xl p-6">

                <div className="flex justify-between items-center">

                    <div>

                        <p className="text-slate-300 text-sm">

                            Final Decision

                        </p>

                        <h1 className="text-5xl font-bold text-cyan-400 mt-2">

                            {decision.decision ?? "--"}

                        </h1>

                    </div>

                    <div className="text-right">

                        <p className="text-slate-300 text-sm">

                            Confidence

                        </p>

                        <h2 className="text-4xl font-bold text-green-400">

                            {

                                Math.round(

                                    (decision.confidence ?? 0) * 100

                                )

                            }%

                        </h2>

                    </div>

                </div>

            </div>

            <div className="mt-6 bg-slate-950 border border-slate-800 rounded-xl p-5">

                <div className="flex items-center gap-2 mb-3">

                    <BadgeCheck

                        size={18}

                        className="text-cyan-400"

                    />

                    <h3 className="text-white font-semibold">

                        AI Reasoning

                    </h3>

                </div>

                <p className="text-slate-300 leading-7">

                    {

                        decision.reasoning ??

                        "No reasoning available."

                    }

                </p>

            </div>

            <div className="grid grid-cols-1 xl:grid-cols-2 gap-5 mt-6">

                <Section

                    title="Supporting Evidence"

                    items={decision.evidence}

                    icon={FileText}

                />

                <Section

                    title="Identified Risks"

                    items={decision.risks}

                    icon={AlertTriangle}

                />

            </div>

            <div className="mt-6">

                <Section

                    title="Recommended Actions"

                    items={decision.recommendations}

                    icon={CheckCircle2}

                />

            </div>

            <div className="mt-6 bg-slate-950 border border-slate-800 rounded-xl p-5">

    <h3 className="text-white font-semibold text-lg mb-4">

        Human-in-the-Loop Review

    </h3>

    <p className="text-slate-400 mb-5">

        Review the AI recommendation before execution.

    </p>

    <div className="flex flex-wrap gap-4">

        <button

            onClick={() => setReviewStatus("Approved")}

            className="bg-green-600 hover:bg-green-700 text-white px-5 py-3 rounded-xl"

        >

            ✅ Approve

        </button>

        <button

            onClick={() => setReviewStatus("Rejected")}

            className="bg-red-600 hover:bg-red-700 text-white px-5 py-3 rounded-xl"

        >

            ❌ Reject

        </button>

        <button

            onClick={() => setReviewStatus("Manual Review Required")}

            className="bg-yellow-500 hover:bg-yellow-600 text-black px-5 py-3 rounded-xl"

        >

            📝 Request Review

        </button>

    </div>

    {reviewStatus && (

    <div className="mt-5">

        <p className="text-slate-400 mb-3">

            Current Status

        </p>

        <span
            className={`px-5 py-2 rounded-full font-semibold

            ${
                reviewStatus === "Approved"

                ? "bg-green-600 text-white"

                : reviewStatus === "Rejected"

                ? "bg-red-600 text-white"

                : "bg-yellow-500 text-black"
            }
            `}
        >

            {
                reviewStatus === "Approved"

                ? "🟢 Approved"

                : reviewStatus === "Rejected"

                ? "🔴 Rejected"

                : "🟡 Pending Manual Review"
            }

        </span>

    </div>

)}

</div>

        </div>

    );

}

export default DecisionCard;